# Generated by Django 5.0.2 on 2024-03-23 08:57

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.CharField(max_length=50, validators=[main.models.validate_no_digits, main.models.clean_name], verbose_name='Category:'),
        ),
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateTimeField(validators=[main.models.clean_name], verbose_name='Publication date:'),
        ),
        migrations.AlterField(
            model_name='news',
            name='full_text',
            field=models.TextField(max_length=200, validators=[main.models.clean_name], verbose_name='Publication:'),
        ),
        migrations.AlterField(
            model_name='news',
            name='name',
            field=models.CharField(max_length=30, validators=[main.models.validate_no_digits, main.models.clean_name], verbose_name='Name:'),
        ),
    ]
